name        : gnome-themes-standard
version     : 3.18.0
release     : 11
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-themes-standard/3.18/gnome-themes-standard-3.18.0.tar.xz : e646eb04c225282b7df7fff65741adaad4cf9ed2c12616b7310e7edd27d2bacb
license     :
    - GPL-2.0
summary     : The Standard GNOME3 Themes Package
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
description : |
    The GNOME Themes Standard package contains various components of the default GNOME 3 theme.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
