name       : gnome-themes-standard
version    : 3.22.3
release    : 15
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-themes-standard/3.22/gnome-themes-standard-3.22.3.tar.xz : 61dc87c52261cfd5b94d65e8ffd923ddeb5d3944562f84942eeeb197ab8ab56a
license    :
    - GPL-2.0
summary    : The Standard GNOME3 Themes Package
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(atk)
    - pkgconfig(gtk+-3.0)
    - pkgconfig32(freetype2)
    - pkgconfig32(fontconfig)
    - pkgconfig32(librsvg-2.0)
component  : desktop.gnome.core
emul32     : yes
description: |
    The GNOME Themes Standard package contains various components of the default GNOME 3 theme.
setup      : |
    # We only have emul32 gtk2 right now.
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --disable-gtk3-engine --enable-gtk2-engine
    else
        %configure --disable-static
    fi
build      : |
    %make
install    : |
    %make_install
