name       : gnome-themes-standard
version    : 3.18.0
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-themes-standard/3.18/gnome-themes-standard-3.18.0.tar.xz : e646eb04c225282b7df7fff65741adaad4cf9ed2c12616b7310e7edd27d2bacb
license    :
    - GPL-2.0
summary    : The Standard GNOME3 Themes Package
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(atk)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig32(librsvg-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The GNOME Themes Standard package contains various components of the default GNOME 3 theme.
setup      : |
    # We only have emul32 gtk2 right now.
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --disable-gtk3-engine --enable-gtk2-engine
    else
        %configure --disable-static
    fi
build      : |
    %make
install    : |
    %make_install
