name       : gnome-themes-standard
version    : 3.22.3
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-themes-standard/3.22/gnome-themes-standard-3.22.3.tar.xz : 61dc87c52261cfd5b94d65e8ffd923ddeb5d3944562f84942eeeb197ab8ab56a
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : The Standard GNOME3 Themes Package
description: |
    The GNOME Themes Standard package contains various components of the default GNOME 3 theme.
emul32     : yes
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(gtk+-3.0)
    - pkgconfig32(librsvg-2.0)
    - pkgconfig32(xrender)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
